# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec2a724f6c87a0d51b2a4c621bb442fabe6ce79f3c0a529fec77ceef60ba4b5bfc933911239543822db32564a365e5c3c89ed012b4dea29f56564cf4703abe3

test:
  secret_key_base: d06a1d8006897dc6dcb00b581b679efbb1a1ea0bd0aabb02feb8730813c4b9c2fb8299b30f530a576f089bb34f51821687dd4a850a75f5d40c488bdbfe3e8f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
